
public enum ERepType {
    ORDER, LEVEL_LIST, LEVEL_ARRAY, LEVEL, TREE ,LEVEL_LIST2,LEVEL_LIST3,LEVEL_LIST4,LEVEL_LIST5,LEVEL_LIST02
    ,LEVEL_LIST6,LEVEL_LIST7,LEVEL_LIST8,LEVEL_LIST9,LEVEL_LIST10,LEVEL_LIST11,LEVEL_LIST10A,LEVEL_LIST10B
}
